name: Deploy Hexo Theme

on:
  push:
    branches: [ master, okwillbe-patch ]
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Echo
        run: echo "Hello, the script is working!"
